{
 "title": "Jenkins",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "tags": [ "jenkins" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Job Queue Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Threads by State",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Plugins by State",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_active{instance=~\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "jenkins_plugins_inactive{instance=~\"$instance\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "jenkins_plugins_failed{instance=~\"$instance\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "jenkins_plugins_withUpdate{instance=~\"$instance\"}",
     "legendFormat": "with update"
    }
   ]
  },
  {
   "title": "JVM Free Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vm_memory_total_max{instance=~\"$instance\"} - vm_memory_total_used{instance=~\"$instance\"}) / vm_memory_total_max{instance=~\"$instance\"} * 100.0"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_total_used{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Nodes Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_offline_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_cpu_load{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Executor Free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_free_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Executors Busy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_executors_busy{instance=~\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Executors Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(jenkins_job_building_duration{instance=~\"$instance\"})/sum(jenkins_job_building_duration_count{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Jobs and Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_count_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last Build Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(default_jenkins_builds_last_build_result_ordinal{instance=~\"$instance\"} == 2)"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, max by (jenkins_job) ({__name__=~\"default\\\\_?jenkins_builds_last_build_duration_milliseconds\", instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disabled Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_total_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sucessful Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_success_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unstable Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_unstable_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Builds Health Score = 0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score{instance=~\"$instance\",buildable=\"true\"} == 0",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Jenkins Queue Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_size_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_failure_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Aborted Builds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_runs_aborted_total{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Web UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Web Request Rate by Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_responseCodes_ok_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(http_responseCodes_created_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "201"
    },
    {
     "expr": "rate(http_responseCodes_noContent_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "204"
    },
    {
     "expr": "rate(http_responseCodes_notModified_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "304"
    },
    {
     "expr": "rate(http_responseCodes_badRequest_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "400"
    },
    {
     "expr": "rate(http_responseCodes_forbidden_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "403"
    },
    {
     "expr": "rate(http_responseCodes_notFound_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "404"
    },
    {
     "expr": "rate(http_responseCodes_serverError_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "500"
    },
    {
     "expr": "rate(http_responseCodes_serviceUnavailable_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "503"
    },
    {
     "expr": "rate(http_responseCodes_other_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "HTTP Request Duration by Quantile",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_requests{instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}